//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub mod prelude;

pub mod analytics;
pub mod attachments;
pub mod messages;
pub mod replies;
pub mod tags;
pub mod ticket_tags;
pub mod tickets;
pub mod users;
