//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::analytics::Entity as Analytics;
pub use super::attachments::Entity as Attachments;
pub use super::messages::Entity as Messages;
pub use super::replies::Entity as Replies;
pub use super::tags::Entity as Tags;
pub use super::ticket_tags::Entity as TicketTags;
pub use super::tickets::Entity as Tickets;
pub use super::users::Entity as Users;
