//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::agent_tags::Entity as AgentTags;
pub use super::agents::Entity as Agents;
pub use super::images::Entity as Images;
pub use super::tags::Entity as Tags;
pub use super::ticket_history::Entity as TicketHistory;
pub use super::tickets::Entity as Tickets;
pub use super::users::Entity as Users;
