//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tag_id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agent_tags::Entity")]
    AgentTags,
}

impl Related<super::agent_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentTags.def()
    }
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        super::agent_tags::Relation::Agents.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::agent_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
